import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, Redacted_Script } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "@/providers/SWRProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const primaryFont = Raleway({
  weight: ["500", "600", "800"],
  subsets: ["latin"],
});
const loadingFont = Redacted_Script({
  weight: ["400"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={
        {
          "--font-family-primary": primaryFont.style.fontFamily,
          "--font-family-loading": loadingFont.style.fontFamily,
        } as any
      }
    >
      <SWRProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </SWRProvider>
    </html>
  );
}
